<?php

namespace Pstryk\AppBundle\Entity;

/**
 * DownstreamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DownstreamRepository extends \Doctrine\ORM\EntityRepository
{
}
