<?php

namespace Pstryk\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DownstreamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DownstreamRepository {
    
    /**
     * @var EntityRepository 
     */
    private $entityRepository;
    
    public function __construct(EntityRepository $entityRepository) {
        $this->entityRepository = $entityRepository;
    }

}
